file:
  client-path: /file
  storage-location: C:/Users/TUF/Desktop/ite-pic\
  base-uri: http://localhost:${server.port}${file.client-path}/

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ite3_ecommerce
    username: postgres
    password: 123456789
  application:
    name: ITE3-ecommerce
server:
  port: 8080