spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ite3_ecommerce
    username: postgres
    password: 123456789
  application:
    name: ITE3-ecommerce
server:
  port: 8080