file:
  client-path: /file
  storage-location: C:/Users/TUF/Desktop/ite-pic\
  base-uri: http://localhost:${server.port}${file.client-path}/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/ite-ecommerce
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ite3_ecommerce
    username: postgres
    password: 123456789
  application:
    name: ITE3-ecommerce
server:
  port: 8080

keycloak:
  server-url: http://localhost:9999
  realm: master
  target-realm: ite-ecommerce
  client-id: ite-ecommerce-spring-api
  client-secret: eyftVgciJBa7ZmKRWcbBouE0k6Zx0Fhi